changed cicd

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -30,6 +30,11 @@ jobs:
         run: mvn test
         working-directory: backend
 
+      # If any previous steps fail, terminate the workflow with a failure
+      - name: Fail on errors
+        if: ${{ failure() }}
+        run: exit 1
+
     # - name: Deploy
     #   # Add your deployment commands here
 
@@ -49,6 +54,11 @@ jobs:
 
       - name: Build
         run: cd frontend && npm run build
+
+      # If any previous steps fail, terminate the workflow with a failure
+      - name: Fail on errors
+        if: ${{ failure() }}
+        run: exit 1
 
   # - name: Deploy
   #   # Add your deployment commands here
